### ISSUE TITLE
Strange collision path

### ISSUE THREAD

**Issue by davidromani** [shnewto/bevy_collider_gen#20]
Why I'm showing this strange collision path? Is due to a bad transparent background? I'm using `single_heightfield_collider_translated`

![Captura de pantalla 2024-08-26 a les 23 53 18](https://github.com/user-attachments/assets/9b00c4c8-0e92-4c4c-8982-50baaf61a53d)

See original PNG file.
![landscape](https://github.com/user-attachments/assets/c2f9421b-711a-4fef-bbf1-09b3d25ad788)

**Comment by shnewto** [comment]
Hi @davidromani heightfields can't handle overlapping points / heights. They're just a collection of consecutive heights (no sense of x,y). The Rapier 2d docs on colliders are really great for browsing what sort of collider might fit certain use cases.

https://rapier.rs/docs/user_guides/javascript/colliders/#heightfields

(I understand you may be using avian2d rather than rapier but the principals and names still apply)

**Comment by salam99823** [comment]
It's because of the bad transparent background too.

**Comment by davidromani** [comment]
@salam99823 I don't know how to see bad transparent pixels inside the image file

**Comment by salam99823** [comment]
I had the same problem, but after erase in this area everything went back to normal. I am tested it with the latest version of `edges`.
